export const GAMESTATUS_ACTIVE = 0
export const GAMESTATUS_CHECKMATE = 10
export const GAMESTATUS_RESIGNED = 11
export const GAMESTATUS_DRAW = 20
export const GAMESTATUS_DRAW_STALEMATE = 21
export const GAMESTATUS_DRAW_REPETITION = 22
export const GAMESTATUS_DRAW_FIFTYMOVES = 23
export const GAMESTATUS_DRAW_NOMATERIAL = 24

export type GameStatus =
	| typeof GAMESTATUS_ACTIVE
	| typeof GAMESTATUS_CHECKMATE
	| typeof GAMESTATUS_RESIGNED
	| typeof GAMESTATUS_DRAW
	| typeof GAMESTATUS_DRAW_STALEMATE
	| typeof GAMESTATUS_DRAW_REPETITION
	| typeof GAMESTATUS_DRAW_FIFTYMOVES
	| typeof GAMESTATUS_DRAW_NOMATERIAL
